apiVersion: v1
kind: Pod
metadata:
  labels:
    app: tvshows
spec:
  securityContext:
    runAsUser: 0
  containers:
    - name: yarn
      image: 'gcr.io/cloud-builders/yarn'
      command:
        - cat
      tty: true
      env:
        - name: HOME
          value: /home/jenkins
      volumeMounts:
        - mountPath: /tmp/workspace
          name: workspace-volume
      resources:
        limits:
          cpu: 4
          memory: 5Gi
          ephemeral-storage: 2Gi
        requests:
          cpu: 0.2
          memory: 1Gi
          ephemeral-storage: 0.2Gi
    - name: mailhog
        image: 'mailhog/mailhog:latest'
        command:
          - cat
        tty: true
        ports:
          - containerPort: 8025
            name: mailhog-service-port
          - containerPort: 1025
            name: smtp-port
        env:
          - name: HOME
            value: /home/jenkins
          - name: MH_STORAGE
            value: maildir
          - name: MH_MAILDIR_PATH
            value: /tmp/workspace/mailhog
        volumeMounts:
          - mountPath: /tmp/workspace/mailhog
            name: mailhog-volume
        resources:
          limits:
            cpu: 4
            memory: 5Gi
            ephemeral-storage: 2Gi
          requests:
            cpu: 0.2
            memory: 1Gi
            ephemeral-storage: 0.2Gi